--EJ 4--
DECLARE
  V_NOMBRE CENTROS.NOMBRE%TYPE;
BEGIN 
  SELECT NOMBRE INTO V_NOMBRE FROM CENTROS WHERE UPPER(NOMBRE)='ABRERA';
  IF SQL%FOUND
  THEN
    DBMS_OUTPUT.PUT_LINE('ESTE CENTRO YA EXISTE');   
  END IF;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO CENTROS(NOMBRE) VALUES('ABRERA');
    IF SQL%NOTFOUND
    THEN 
      DBMS_OUTPUT.PUT_LINE('NINGUN REGISTRO INSERTADO');
    ELSE
      DBMS_OUTPUT.PUT_LINE('INSERTADO OK');
      COMMIT;
    END IF;
  WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('EXISTE MÁS DE UN CENTRO CON ESTE NOMBRE');
END;